export const NO_MODE = -1
export const FACE_DETECTION_MODE = 1
export const VISION_URL = 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.12/wasm'
export const DELEGATE_GPU = 'GPU'
export const RUNNING_MODE_VIDEO = 'VIDEO'
export const FACE_DETECTION_STR = 'Face Detection'
export const VIDEO_INPUT = 'videoinput'
export const CAMERA_LOAD_STATUS_SUCCESS = 1
export const CAMERA_LOAD_STATUS_ERROR = 2
export const CAMERA_LOAD_STATUS_NO_DEVICES = 3
export const ERROR_ENABLE_CAMERA_PERMISSION_MSG = 'Please Enable Camera Permission'
export const ERROR_NO_CAMERA_DEVICE_AVAILABLE_MSG = 'No Camera Device Available'
